apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # MySQL
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  # dm-rust 应用
  - dm-rust-configmap.yaml
  - dm-rust-pvc.yaml
  - dm-rust-deployment.yaml
  - dm-rust-service.yaml

commonLabels:
  project: dm-rust
